# Generated by Django 4.2.17 on 2025-03-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='end_time',
        ),
        migrations.AddField(
            model_name='screening',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
